#!/bin/sh
set -e

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
    echo "Running py3compile for python3-thingsboard-gateway..."
    py3compile -p python3-thingsboard-gateway
fi
if which pypy3compile >/dev/null 2>&1; then
    echo "Running pypy3compile for python3-thingsboard-gateway..."
    pypy3compile -p python3-thingsboard-gateway || true
fi

echo "Checking if /var/lib/thingsboard_gateway/ exists..."
if [ ! -d "/var/lib/thingsboard_gateway/" ]; then
    echo "Creating /var/lib/thingsboard_gateway/ directory..."
    mkdir -p /var/lib/thingsboard_gateway/
else
    echo "/var/lib/thingsboardes_gateway/ already exists."
fi
echo "Checking if /etc/thingsboard-gateway/extensions exists..."
if [ ! -d "/etc/thingsboard-gateway/extensions" ]; then
    sudo mkdir -p /etc/thingsboard-gateway/extensions
    echo "Created /etc/thingsboard-gateway/extensions directory"
else
    echo "/etc/thingsboard-gateway/extensions directory already exists. Skipping creation."
fi

echo "Checking if /etc/thingsboard-gateway/rpc exists..."
if [ ! -d "/etc/thingsboard-gateway/rpc" ]; then
    sudo mkdir -p /etc/thingsboard-gateway/rpc
    echo "Created /etc/thingsboard-gateway/rpc directory"
else
    echo "/etc/thingsboard-gateway/rpc directory already exists. Skipping creation."
fi

# Copy necessary files and set permissions
echo "Copying extensions to /etc/thingsboard-gateway/extensions/..."
sudo cp -a -r  /var/lib/thingsboard_gateway/extensions /etc/thingsboard-gateway/extensions
echo "Removing /var/lib/thingsboard-gateway/extensions..."
sudo rm -r /var/lib/thingsboard_gateway/extensions

echo "Adding users to dialout and thingsboard_gateway groups..."
sudo usermod -a -G dialout $USER
sudo usermod -a -G dialout thingsboard_gateway
sudo usermod -a -G thingsboard_gateway $USER

VENV_PATH="/var/lib/thingsboard_gateway/venv"

# Create virtual environment if it doesn't exist
echo "Checking for virtual environment at $VENV_PATH..."
if [ ! -d "$VENV_PATH" ]; then
    echo "Creating Python virtual environment..."
    python3 -m venv "$VENV_PATH"
else
    echo "Removing previous virtual environment"
    rm -rf "$VENV_PATH"
    python3 -m venv "$VENV_PATH"
fi

echo "Setting permissions for /var/log/thingsboard-gateway/..."
sudo chown thingsboard_gateway:thingsboard_gateway /var/log/thingsboard-gateway/ -R
echo "Setting permissions for /var/lib/thingsboard_gateway/..."
sudo chown thingsboard_gateway:thingsboard_gateway /var/lib/thingsboard_gateway/ -R
echo "Setting permissions for /etc/thingsboard-gateway/..."
sudo chown thingsboard_gateway:thingsboard_gateway /etc/thingsboard-gateway/ -R

# Activate the virtual environment and install required dependencies
echo "Upgrading pip and installing required dependencies..."
"$VENV_PATH/bin/pip" install --upgrade pip

echo "Getting wheel package name..."
echo $(ls /var/lib/thingsboard_gateway/)
WHEEL_FILE=$(ls /var/lib/thingsboard_gateway/*.whl)
echo "Installing wheel package $WHEEL_FILE..."
"$VENV_PATH/bin/pip" install $WHEEL_FILE

# Modify the logs config file
echo "Updating logs configuration..."
sudo sed -i 's/\.\/logs/\/var\/log\/thingsboard-gateway/g' /etc/thingsboard-gateway/config/logs.json >> /etc/thingsboard-gateway/config/logs.json

# Enable and start the service
echo "Enabling daemon..."
sudo pidof systemd && sudo systemctl enable thingsboard-gateway || echo "Systemctl not found, cannot enable the daemon!"
echo "Starting daemon..."
sudo pidof systemd && sudo systemctl start thingsboard-gateway || echo "Systemctl not found, cannot start the daemon!"
echo -e "\e[96mThingsBoard Gateway \e[92mhas been installed. Have a nice day \e[93m\e[5m:)\e[25m\e[39m"
